### ISSUE TITLE
World Edit //set Command! Bugged.

### ISSUE THREAD

**Issue by Gamxr** [Minehut/Issues#43]
Here is the issue it gives me in-game.
Link: http://com.google.common.base.Objects.firstNonNull(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object

Proof of the chat error. 

Link http://prntscr.com/fhpmw1

**Comment by MatrixTunnel** [comment]
I updated the plugin to use the new version but I think it might have broken some things. I'm going to downgrade it but some things might be broken

**Comment by MatrixTunnel** [comment]
Ok, even after downgrading it was still broken. WorldEdit released an update and I pushed that to the network

**Comment by AttendantFox** [comment]
I've tried //set on my server and it's not fixed @MatrixTunnel

**Comment by MatrixTunnel** [comment]
Has there been any issues with this? It should be working

**Comment by MatrixTunnel** [comment]
Seems to be fixed
